#!/bin/bash

# Helper script for common anime stuff

METADIR=$HOME/anime-metadata
ACTION=$1
shift

case $ACTION in
    list)
        ls "$METADIR"
        ;;
    db)
        . "$METADIR/$1"
        anidb -aw "$ANIMEDIR/"*$2*
        ;;
    dl)
        . "$METADIR/$1"
        printf "Searching for: $ANIMESEARCH\n" $2
        nyaadl.sh "$(printf "$ANIMESEARCH" $2)"
        ;;
    torr)
        . "$METADIR/$1"
        deluge-console "add \"$2\" --path \"$ANIMEDIR\""
        ;;
    cal)
        . "$METADIR/$1"
        animecal "$ANIMECALENDAR" $2 $3
        ;;
    *)
        cat <<EOF
Actions available:
  list
  db
  dl
  torr
  cal
EOF
        ;;
esac
